server:
  port: 30000
spring:
  application:
    name: xianlai-app-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        username: ${nacos.username}
        password: ${nacos.password}
      config:
        import-check: # 启动时自动检查配置文件是否符合规范
          enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  config: classpath:logback-spring.xml
  # 日志级别 FATAL > ERROR > WARN > INFO > DEBUG > TRACE
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.boot.web.embedded: INFO
    org.apache: WARN
    fun.xianlai: INFO
